[package]
name = "v8_live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8="0.63.0"
serde_v8="0.84.0"
