[package]
name = "simple-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
bytes = "1.6.0"
tokio = { version = "1.37.0", features = ["rt", "tokio-macros", "rt-multi-thread", "net", "io-util"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
