[package]
name = "testDome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="kvc"
path="src/client.rs"

[[bin]]
name="kvs"
path="src/server.rs"

[dependencies]
